language: perl
dist:     trusty
sudo:     false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libluajit-5.1-2
      - libluajit-5.1-dev
      - lua-cjson

env:
  global:
    - LUAJIT_LIB=/usr/lib/x86_64-linux-gnu/
    - LUAJIT_INC=/usr/include/luajit-2.0/
    - VER_LUA_NGINX=0.10.7
    - VER_NGINX=1.11.10

install: cpanm -v --notest Test::Nginx
script:  ./compile_and_test.sh
